// Generated by pnpm contracts:freeze.
export const contentManifest = {
  "version": "G0-1",
  "schemaDigests": {
    "bot-definition": "0574713283466ec37b620375cb4014736ff8cdfae821ac701e8312ba1d64a7fc",
    "body": "f463621575687a504524bc1abb5ed33cae30e53bd3575ea686dee34bd3b8d310",
    "brain": "e242df172a3f8fdac86170135dcd0ea94884e0a1756caf0a900eec1ebdfdb5d7",
    "ir": "6656cdd51db0148b44fdb6ad7100098faa19b932a0017becabdd2c200289a98a",
    "compiled-brain": "1f4d58b149ba6ca400a7c9311f54589e91c538577d35b48aabbc11cf872538a5",
    "bot-package": "51685b3caab1302bf97e209a30d460cb89adcfc85cc8f33eeddaf9e3f40b5812",
    "intent": "bb3c4b8032a1b1a2124e681615b9697ef54330924566a69e3201afbddd5dd7c9",
    "observation": "18bdb319488ad17ed878a8892444c183f45293ddbd74ee96b5ff58b55c3b5594",
    "validation": "95b509e31ab5ad7b37a22ab2bacc15577f4ba278e08eabc47b72370d7ae4f621",
    "experiment-spec": "9d41e29489d7b70c7063809188ce4e4d49001b9eaa735db939121bf73ccd6479",
    "experiment": "78f3ee3b52000a993e0e3c148a6e919b69f684746f0f9ff081807e1cb60cbbb1",
    "match": "137b717c19b032579da65339c9152012b9f0084f68548bb087aef8417049d134",
    "match-result": "ae79a28ea16e87b73fb2b3dd71aae0e0a27cc16997be26e513ab9a0201100caa",
    "replay": "706df6b108b1d3884906d16a56ade351f639f61c9c32680fad9f2abbd39131f0",
    "ratings": "893c9c7ee331a910231462c0166b9e0f4b8923f891c73e8bd5d1ae61ab10dfea"
  },
  "compilerDigest": "2fafc70e15f577f697c4224d00da9a5c1e353ee43815e965b8a869ae3c4983ee",
  "catalogDigest": "d8fe55474692a49ed5daa6d7dac62f635630a9e447a85ba683c0765bf535885d",
  "rulesetDigest": "19ef0b984d12a34796ea2058bb9971421674671fd4cc76b8cf694e80f03d2f14",
  "arenaInitDigest": "213af97e3969c88fce81f28e1055c18af8549bbf5bd37e72079f1d301d4ba510",
  "lutDigest": "749eadf6445c275c6b7cc7a2fc3fa1012775af6bdab7853753a28ae378336de1",
  "capabilityDigest": "183be2a086910659afdd918061d22fd3289f9a6ce9bb0644872f5997e83cd353"
} as const;
