import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const contracts=await import('../packages/contracts/dist/index.js');
const dir='packages/contracts/schemas';await mkdir(dir,{recursive:true});
const schemaDigests={};
for(const [name,schema] of Object.entries(contracts.schemas)){
  const bytes=contracts.canonical(schema);schemaDigests[name]=hash(bytes);await writeFile(`${dir}/${name}.json`,bytes+'\n');
}
const sources=[];
for(const packageName of ['brain','contracts'])for(const name of await readdir(`packages/${packageName}/src`))if(name.endsWith('.ts')&&name!=='identity.ts')sources.push(`packages/${packageName}/src/${name}`);
sources.sort();
const compilerDigest=hash((await Promise.all(sources.map(async name=>name+'\n'+await readFile(name,'utf8')))).join('\n'));
await writeFile('packages/brain/src/identity.ts',`// SHA256 of sorted brain and contracts sources (excluding this identity file).\nexport const COMPILER_DIGEST = '${compilerDigest}';\n`);
const content=await import('../packages/content/dist/index.js');
const catalogDigest=await contracts.digest(content.catalog),rulesetDigest=await contracts.digest(content.ruleset),arenaInitDigest=await contracts.digest(content.arenaPresets),lutDigest=await contracts.digest({SIN:content.SIN,COS:content.COS});
const capabilityDigest=await contracts.digest({abi:'2.0',sensors:(await import('../packages/brain/dist/index.js')).SENSORS,moduleSensors:['self.weaponReady.<ordinal>','self.moduleAlive.<ordinal>']});
const manifest={version:'G0-1',schemaDigests,compilerDigest,catalogDigest,rulesetDigest,arenaInitDigest,lutDigest,capabilityDigest};
await mkdir('packages/content/data',{recursive:true});
for(const [name,value] of Object.entries({catalog:content.catalog,ruleset:content.ruleset,'arena-init':content.arenaPresets,'reference-kits':content.referenceKits,manifest,suite:await content.buildSuite()}))await writeFile(`packages/content/data/${name}.json`,JSON.stringify(value,null,2)+'\n');
await writeFile('packages/content/src/manifest.ts',`// Generated by pnpm contracts:freeze.\nexport const contentManifest = ${JSON.stringify(manifest,null,2)} as const;\n`);
const result=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','-b'],{stdio:'inherit'});if(result.status!==0)process.exit(result.status??1);
console.log(JSON.stringify(manifest,null,2));
