import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir,writeFile,readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { join,resolve } from 'node:path';
import os from 'node:os';
const require=createRequire(import.meta.url);
let playwright;try{playwright=require('playwright');}catch{const bundle=process.env.PLAYWRIGHT_MODULE??join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');playwright=require(bundle);}
const output=process.env.G2_QA_DIR??'.local/g2/qa',port=5187,url=`http://127.0.0.1:${port}`;
await mkdir(`${output}/screenshots`,{recursive:true});
const server=spawn(process.execPath,[resolve('apps/web/node_modules/vite/bin/vite.js'),'preview','--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:'apps/web',stdio:['ignore','pipe','pipe']});let serverOutput='';server.stdout.on('data',d=>serverOutput+=d);server.stderr.on('data',d=>serverOutput+=d);
const report={status:'running',startedAt:new Date().toISOString(),runtime:process.version,platform:process.platform,cpu:os.cpus()[0]?.model,logicalCpus:os.cpus().length,ramBytes:os.totalmem(),browser:'',browserChannel:process.env.G2_BROWSER??'chrome',checks:[],pageErrors:[],consoleErrors:[],metrics:{},unrun:['Actual human usability/readability/counterplay','Actual mobile hardware','Safari/Firefox','Independent art reviewer','Full WCAG/manual screenreader review']};
const check=(name,detail)=>report.checks.push({name,status:'passed',detail});let browser;
try{
  for(let i=0;i<100;i++){if(server.exitCode!==null)throw new Error(serverOutput);try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await playwright.chromium.launch({channel:process.env.G2_BROWSER??'chrome',headless:true});report.browser=browser.version();
  const context=await browser.newContext({viewport:{width:1600,height:1100},deviceScaleFactor:1,acceptDownloads:true});
  await context.addInitScript(()=>{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(url,options){const fail=window.__failNextWorker;window.__failNextWorker=false;const fault=fail?URL.createObjectURL(new Blob(["onmessage=()=>{throw new Error('G2_FAULT_INJECTION')}"])):url;super(fault,options);this.addEventListener('message',e=>{if(e.data.kind==='match')window.__lastMatch=e.data;if(e.data.kind==='validate')window.__lastValidation=e.data;});}};});
  const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});
  const button=name=>page.getByRole('button',{name,exact:true}),status=()=>page.getByRole('status');
  await page.goto(url);await page.locator('#synth-name').waitFor();await page.screenshot({path:`${output}/screenshots/workshop.png`,fullPage:true});
  check('Boot / authored assets / initial draft',await page.locator('#synth-name').inputValue());
  await page.getByLabel('Âm UI',{exact:true}).check();await button('Brain Lab').click();await button('Workshop').click();await page.getByLabel('Âm lượng UI',{exact:true}).evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'.3');el.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>localStorage.getItem('prompt-chien-ui-volume')==='0.3');await page.getByLabel('Âm UI',{exact:true}).uncheck();check('Independent gesture-gated UI audio and volume controls',true);
  // Place adjacent armor, move/rotate/remove it, then exercise both history directions.
  await page.getByRole('button',{name:'Ô 7,6 · trống',exact:true}).click();await button('Đặt Giáp (7,6)').click();await button('Kiểm tra bot').click();await status().filter({hasText:'hợp lệ'}).waitFor();
  assert.equal(await page.evaluate(()=>window.__lastValidation.bot.body.modules.length),7);
  await button('Hoàn tác').click();await button('Làm lại').click();await page.getByRole('button',{name:/Ô 7,6 · Giáp/}).click();await button('Xoay 90°').click();await button('Xóa module').click();await button('Hoàn tác').click();await button('Hoàn tác').click();await button('Hoàn tác').click();
  await button('Kiểm tra bot').click();await status().filter({hasText:'hợp lệ'}).waitFor();assert.equal(await page.evaluate(()=>window.__lastValidation.bot.body.modules.length),6);check('Body place / rotate / delete / undo / redo',true);
  const cell=page.locator('[data-cell="7,6"]');await cell.focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.locator(':focus').getAttribute('data-cell'),'6,6');check('Keyboard grid / focus navigation',true);
  // Imports pass through the bounded duplicate-key parser, preserving an unapplied buffer across tabs.
  await button('Import / export JSON').click();const text=await page.getByLabel('Bot JSON',{exact:false}).inputValue();
  await page.getByLabel('Bot JSON',{exact:false}).fill('{"schemaVersion":"2.0","schemaVersion":"2.0"}');await button('Kiểm tra và áp dụng JSON').click();await page.getByRole('alert').filter({hasText:'DUPLICATE_KEY'}).waitFor();
  await button('Brain Lab').click();await button('Workshop').click();assert.match(await page.getByLabel('Bot JSON',{exact:false}).inputValue(),/schemaVersion/);
  await page.getByLabel('Bot JSON',{exact:false}).fill(text);await button('Kiểm tra và áp dụng JSON').click();await status().filter({hasText:'hợp lệ'}).waitFor();check('Bounded import / duplicate key pointer / unapplied buffer retained',true);
  await button('Lưu revision').click();await status().filter({hasText:'Đã lưu revision 1'}).waitFor();await page.reload();await page.locator('#synth-name').waitFor();assert.match(await page.locator('main').innerText(),/REVISION 1/);check('IndexedDB revision reload',true);
  // Two tabs race the same stored revision; the stale tab must keep its work.
  const second=await context.newPage();await second.goto(url);await second.locator('#synth-name').waitFor();await page.locator('#synth-name').fill('Mantis local r2');await button('Lưu revision').click();await status().filter({hasText:'Đã lưu revision 2'}).waitFor();
  await second.locator('#synth-name').fill('Bản riêng của tab 2');await second.getByRole('button',{name:'Lưu revision',exact:true}).click();await second.getByRole('alert').filter({hasText:'Tab khác đã lưu'}).waitFor();assert.equal(await second.locator('#synth-name').inputValue(),'Bản riêng của tab 2');await second.close();check('Two-tab CAS rejects stale save without overwriting unsaved draft',true);
  await button('Khóa baseline hiện tại').click();await button('Brain Lab').click();await page.getByLabel('Tiến/lùi (−1000…1000)',{exact:true}).fill('900');await button('Kiểm tra bot').click();await status().filter({hasText:'hợp lệ'}).waitFor();await page.screenshot({path:`${output}/screenshots/brain-lab.png`,fullPage:true});
  const rule=await page.getByLabel('Rule JSON · condition / intent / set / nextState').inputValue();await page.getByLabel('Rule JSON · condition / intent / set / nextState').fill(rule.replace('900','850'));await button('Kiểm tra và áp dụng luật').click();await status().filter({hasText:'hợp lệ'}).waitFor();check('Structured Brain field + rule source compilation',true);
  await page.getByLabel('Scenario',{exact:false}).selectOption('3');await button('Chạy A/B (12 legs)').click();await page.locator('.comparison').waitFor({timeout:180000});await page.locator('canvas').waitFor();
  const match=await page.evaluate(()=>{const r=window.__lastMatch;return {comparison:r.comparison,manifest:r.replay.manifest,result:r.replay.result,simulationHash:r.replay.simulationHash,publicReplayHash:r.replay.publicReplayHash,frameCount:r.replay.frames.length,ownerCount:r.replay.owner.traces.length,publicKeys:Object.keys(r.replay.frames[0].actors.A),traceContainsB:r.replay.owner.traces.some(t=>'actor' in t)}});
  assert.equal(match.comparison.rows.length,3);assert.equal(new Set(match.comparison.rows.map(r=>r.scenarioId)).size,3);assert.equal(match.comparison.confidence,null);assert.notEqual(match.comparison.baselineHash,match.comparison.candidateHash);
  for(const row of match.comparison.rows){assert.equal(row.legs.length,4);assert.deepEqual(row.legs.map(l=>[l.variant,l.swap]),[['baseline',false],['baseline',true],['candidate',false],['candidate',true]]);}assert.equal(match.traceContainsB,false);assert(!match.publicKeys.includes('energy'));report.localExperiment=match;check('3 paired scenarios / 12 legs / exact bindings / public-private split',true);
  await page.screenshot({path:`${output}/screenshots/arena.png`,fullPage:true});
  const windup=await page.evaluate(()=>window.__lastMatch.replay.frames.findIndex(f=>Object.values(f.actors).some(a=>a.modules.some(m=>m.phase==='windup'))));assert(windup>0);
  async function seek(tick){await page.locator('#timeline').evaluate((el,value)=>{const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(el,String(value));el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},tick);await page.waitForTimeout(30);}
  await seek(windup);const first=await page.locator('canvas').screenshot();await seek(0);await seek(match.frameCount-1);await seek(windup);const again=await page.locator('canvas').screenshot();assert(first.equals(again));await page.screenshot({path:`${output}/screenshots/windup.png`,fullPage:true});check('Seek reconstructs identical visual state regardless of seek order',true);
  const seekTimes=[];for(let i=0;i<100;i++){const start=performance.now();await seek((i*137)%match.frameCount);seekTimes.push(performance.now()-start);}seekTimes.sort((a,b)=>a-b);report.metrics.seekRoundTripP95Ms=seekTimes[94];assert(seekTimes[94]<150);check('100 random seeks including browser round-trip',seekTimes[94]);
  await seek(windup);await page.getByLabel('VFX',{exact:true}).uncheck();await page.getByLabel('Thang xám',{exact:true}).check();await page.getByLabel('Chất lượng',{exact:false}).selectOption('low');await page.screenshot({path:`${output}/screenshots/grayscale-low.png`,fullPage:true});assert.equal(await page.evaluate(()=>window.__lastMatch.replay.simulationHash),match.simulationHash);check('Low/VFX-off/grayscale keeps authoritative hash',true);
  await button('Bật âm thanh').click();await button('Tắt âm thanh').waitFor({timeout:30000});await button('Phát').click();await page.waitForTimeout(300);await button('Dừng').click();await seek(0);check('Gesture audio / pause and seek stop transients',true);
  await page.locator('canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2');window.__loseContext=gl?.getExtension('WEBGL_lose_context');window.__loseContext?.loseContext();});await page.getByRole('status').filter({hasText:'Mất kết nối đồ hoạ'}).waitFor();
  await page.evaluate(()=>window.__loseContext.restoreContext());await page.getByRole('status').filter({hasText:'Đồ hoạ đã khôi phục'}).waitFor();assert.equal(await page.locator('#timeline').inputValue(),'0');await page.screenshot({path:`${output}/screenshots/context-restored.png`,fullPage:true});check('Real WEBGL_lose_context recovery retains tick',true);
  await button('Brain trace').click();await seek(13);assert.match(await page.locator('.telemetry').innerText(),/\/brain\/states\/0\/rules\//);await page.getByRole('button',{name:'Tạo giả thuyết để thử',exact:true}).first().click();assert.match(await page.getByLabel('Mục tiêu / tấn công / mất bộ phận').inputValue(),/tick/);await button('Lưu revision').click();await status().filter({hasText:'Đã lưu revision 3'}).waitFor();check('Owner source-map trace → debrief hypothesis → persisted revision',true);
  // A terminated job followed by an actual unhandled worker error must be retryable, not a match loss.
  await button('Thử trận').click();await page.evaluate(()=>window.__failNextWorker=true);await button('Hủy job').click();await page.getByRole('alert').filter({hasText:'WORKER_CRASH'}).waitFor();await button('Thử lại cùng đầu vào').click();await page.locator('canvas').waitFor({timeout:90000});await status().filter({hasText:'Trận local đã tính'}).waitFor();check('Cancel / actual worker error / retry same snapshot',true);
  for(const width of [390,320]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${output}/screenshots/mobile-${width}.png`,fullPage:true});await button('Workshop').click();assert(await page.locator('.mobile-note').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await button('Arena').click();}check('390px / 320px mobile summary and replay with no horizontal overflow',true);
  await page.setViewportSize({width:1600,height:1100});await page.emulateMedia({reducedMotion:'reduce'});await button('Brain Lab').click();await button('Arena').click();await page.locator('canvas').waitFor();await seek(windup);await page.screenshot({path:`${output}/screenshots/reduced-motion.png`,fullPage:true});check('Reduced motion retains telegraph and accessible DOM',true);
  const gpu=await page.locator('canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {vendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),version:gl.getParameter(gl.VERSION)};});report.gpu=gpu;
  report.metrics.assetRequests=await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>/\/assets\/|\/fonts\//.test(r.name)).map(r=>({url:r.name,transferBytes:r.transferSize,decodedBytes:r.decodedBodySize})));
  assert.equal(report.pageErrors.length,0);assert.equal(report.consoleErrors.length,0);report.status='passed';
}catch(error){report.status='failed';report.error=String(error);throw error;}
finally{report.finishedAt=new Date().toISOString();await writeFile(`${output}/browser-qa.json`,JSON.stringify(report,null,2)+'\n');await browser?.close();if(server.exitCode===null)server.kill();console.log(JSON.stringify({status:report.status,checks:report.checks.length,output,errors:report.pageErrors},null,2));}
