import { readFile, readdir } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { evidence, save } from './u3d02-evidence.mjs';
const json=async p=>JSON.parse(await readFile(p,'utf8'));
const chrome=await json(`${evidence}/browser-chrome-${process.env.U3D_REPORT_SUFFIX??'release-final'}.json`),edge=await json(`${evidence}/browser-edge-${process.env.U3D_REPORT_SUFFIX??'release-final'}.json`),faults=await json(`${evidence}/faults.json`),manifest=await json('apps/web/public/assets/ui3d/u3d01/manifest.json'),fixture=await json(`${evidence}/fixture.json`);
const unique=[...new Set(fixture.body.modules.map(m=>m.catalogId))],lods={};
for(const quality of ['high','medium','low']){const models=unique.map(id=>manifest.modules.find(m=>m.catalogId===id).levels[quality]);lods[quality]={uniqueTypes:unique,bytes:models.reduce((n,m)=>n+m.bytes,0),instanceTriangles:fixture.body.modules.reduce((n,m)=>n+manifest.modules.find(a=>a.catalogId===m.catalogId).levels[quality].triangles,0),embeddedTextures:true};}
const initial=[...new Map(chrome.initialRequests.filter(r=>r.bytes>0&&!r.url.includes('/high/')).map(r=>[r.url,r])).values()],initialBytes=initial.reduce((n,r)=>n+r.bytes,0)+(await readFile('.local/u3d02/dist/fixture.json')).length;
const root='apps/web/dist',html=await readFile(`${root}/index.html`,'utf8'),main=html.match(/src="(\/assets\/index-[^"]+\.js)"/)[1],assets=await readdir(`${root}/assets`);
const shell=[main.slice(1),...assets.filter(f=>/^(?:index-.*\.css|rolldown-runtime-.*\.js|local\.worker-.*\.js)$/.test(f)).map(f=>`assets/${f}`),'index.html'],shellFiles=[];
for(const file of shell){const data=await readFile(`${root}/${file}`);shellFiles.push({file,bytes:data.length,gzipBytes:gzipSync(data).length});}
const harness=[];for(const f of await readdir('.local/u3d02/dist/assets'))if(/\.(js|css)$/.test(f)){const data=await readFile(`.local/u3d02/dist/assets/${f}`);harness.push({file:f,bytes:data.length,gzipBytes:gzipSync(data).length});}
const report={status:[chrome,edge,faults].every(r=>r.status==='passed')?'passed':'failed',lods,mainAppShell:{files:shellFiles,gzipBytes:shellFiles.reduce((n,f)=>n+f.gzipBytes,0),threeDIntegrated:false},standaloneHarness:{files:harness,warning:'All-in-one test harness includes 3D code; not an integrated application shell. U3D-03 must lazy-load 3D.'},initialAssets:{files:initial,fixtureBytes:(await readFile('.local/u3d02/dist/fixture.json')).length,bytes:initialBytes,limitBytes:8388608,passed:initialBytes<=8388608,highSupplementBytes:lods.high.bytes,note:'Observed Medium + font + floor + manifest + decoder and public fixture; GLB embeds KTX2, sidecars are not counted again; Meshopt runtime is in the JS bundle.'},profiles:Object.fromEntries([['chrome',chrome],['edge',edge]].map(([name,r])=>[name,{browser:r.browser,gpu:r.renders['workshop-high-1600'].gpu,viewport:[1600,1100],dpr:1,qualities:Object.fromEntries(Object.entries(r.profiles).map(([q,p])=>[q,{samples:p.samples.length,cpuP95:p.cpuP95,cpuP99:p.cpuP99,rafP95:p.rafP95,kind:p.kind}])),idleReducedMotion:r.idle,liveAnimation:r.animation?{ms:r.animation.ms,frames:r.animation.frames}:null}])),memory:{...faults.memory,backingStorageDriftBytes:faults.memory.after.backingStorageSize-faults.memory.before.backingStorageSize,warning:'usedSize is JS heap. backingStorageSize is a separate external-buffer reading. Neither is GPU memory; no whole-process/GPU drift claim.'},checks:await json(`${evidence}/final/checks.json`),asset:await json(`${evidence}/assets.json`),appSmoke:await json(`${evidence}/app-smoke.json`)};
report.liveProfile=await json(`${evidence}/live-profile.json`);
report.animation=await json(`${evidence}/${process.env.U3D_ANIMATION??'animation'}.json`);
report.hoverRanges=report.animation.hoverSamples?.[0]?.map(module=>{
 const heights=report.animation.hoverSamples.map(row=>row.find(m=>m.id===module.id).y);
 return{id:module.id,catalogId:module.catalogId,samples:heights.length,min:Math.min(...heights),max:Math.max(...heights)};
})??null;
if(report.liveProfile.status!=='passed'||report.appSmoke.status!=='passed'||report.animation.status!=='passed')report.status='failed';
await save(`${evidence}/measurements${process.env.U3D_REPORT_SUFFIX?'-'+process.env.U3D_REPORT_SUFFIX:''}.json`,report);console.log(JSON.stringify({status:report.status,lods,initialAssetsBytes:initialBytes,shellGzipBytes:report.mainAppShell.gzipBytes,profiles:report.profiles,memory:report.memory},null,2));
